BTN_L = 0
BTN_R = 1
BTN_U = 2
BTN_D = 3
BTN_O = 4
BTN_X = 5

CLR_BLK = 0
CLR_DBL = 1
CLR_PRP = 2
CLR_DGN = 3
CLR_BRN = 4
CLR_DGY = 5
CLR_GRY = 6
CLR_WHT = 7
CLR_RED = 8
CLR_ORN = 9
CLR_YLW = 10
CLR_GRN = 11
CLR_BLU = 12
CLR_IND = 13
CLR_PNK = 14
CLR_PCH = 15

RESOLUTION_X = 128
RESOLUTION_Y = 120

MAX_VEL = 0.8

FRAME_RATE = 60

COUNTDOWN_TIMEOUT = 59

ENT_BOX = 0
ENT_ITEM = 1
ENT_BEAM = 2
ENT_GLOVE = 3
ENT_WH = 4

FLAG_PLAYER = 0
FLAG_FLOOR = 1
FLAG_ABSORBED_BY_GRAV = 2
FLAG_COLLIDES_SELF = 3
FLAG_COLLIDES_PLAYER = 4
FLAG_GAP = 5
FLAG_STAIRS = 6

DIRECTION_UP = 0
DIRECTION_RIGHT = 1
DIRECTION_DOWN = 2
DIRECTION_LEFT = 3

PLAYER_STATE_GROUNDED = "GROUNDED"
PLAYER_STATE_FLOATING = "FLOATING"
PLAYER_STATE_SLIDING = "SLIDING"
PLAYER_STATE_FIRING = "FIRING"
PLAYER_STATE_HOLDING = "HOLDING"
PLAYER_STATE_DEAD_FALLING = "DEAD_FALLING"
PLAYER_STATE_DEAD_ZAPPED = "DEAD_ZAPPED"

ENT_STATE_NORMAL = "NORMAL"
ENT_STATE_BROKEN = "BROKEN"
ENT_STATE_HELD = "HELD"
